name: enviroplus
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.1
  image_picker: ^1.0.7
  intl: ^0.19.0
  logger: ^2.0.2+1
  lottie: ^3.1.0
  ming_cute_icons: ^0.0.4
  percent_indicator: ^4.2.3
  persistent_bottom_nav_bar: ^5.0.2
  provider: ^6.1.2
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/authentication_image/
    - assets/images/pollution/
    - assets/images/products/
    - assets/images/mission/
    - assets/images/content/
    - assets/lottie/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Italic.ttf
          style: italic
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 800
